name: choffer
description: App para motoristas de transporte
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # CLOUDINARY e HTTP
  cloudinary_public: ^0.21.0
  dio: ^5.3.2
  http: ^1.1.0
  crypto: ^3.0.3
  
  # UI básico - APENAS o essencial
  image_picker: ^1.0.4
  intl: ^0.18.1
  
  # Utilities básicos
  shared_preferences: ^2.2.2
  
  # NOVAS DEPENDÊNCIAS PARA FUNCIONALIDADES AVANÇADAS
  # Google Maps
  google_maps_flutter: ^2.5.0
  
  # Localização e GPS
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  
  # WebSocket e tempo real
  web_socket_channel: ^2.4.0
  
  # Notificações Push
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.2.0
  
  # Persistência avançada
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Geocoding (endereço <-> coordenadas)
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Para Hive (persistência)
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets - Declaração dos recursos
  assets:
    - assets/images/